version: "3.4"

services:
  # node:
  #   depends_on:
  #     - mysql
  #   container_name: node
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - ./src:/app/src
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   env_file:
  #     - ../.env
  #   networks:
  #     - internal

  mysql:
    build:
      context: mysql
    container_name: mysql
    restart: always
    networks:
      - internal
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: books
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: books
      MYSQL_PASSWORD: books
    env_file:
      - ./../.env
    volumes:
      - ./opt/app/mysql:/var/lib/mysql
      - ./db/dump:/dump

networks:
  internal: